### PR TITLE
Fix mssql int conversion

### LINKED ISSUE #277: Non-null values are getting imported as null
I have a table with a `[int] IDENTITY(1,1) NOT NULL` column. When I try to import it, pgloader tells me that it contains nulls:

```
2015-08-20T14:31:15.854000-06:00 DEBUG SELECT [thisID], [emailAddress], [flag], convert(varchar, [InsertDate], 126) FROM [dbo].[foo];
2015-08-20T14:31:16.054000-06:00 DATA < #(NIL "example@example.com" 1 "2007-06-05T14:36:15.097")
2015-08-20T14:31:16.765000-06:00 ERROR Database error 23502: null value in column "thisid" violates not-null constraint
DETAIL: Failing row contains (null, example@example.com, t, 2007-06-05 14:36:15.097-06).
CONTEXT: COPY foo, line 1: "\N	example@example.com	t	2007-06-05T14:36:15.097"
```

Running that same query manually shows that thisID is never actually null.

### PR DESCRIPTION
**Pull request by gavinwahl**
The case statement got messed up in commit db0f21b5a5. Fixes #277.

### CODE REVIEW

**Comment by gavinwahl** [comment]
I realized this doesn't completely fix the bug. I get:

```
An unhandled error condition has been signalled:
                              The value -1 is not of type UNSIGNED-BYTE.


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10088DEA73}>
0: (MSSQL::UNSIGNED-TO-SIGNED -1 4) [tl,external]
1: (MSSQL::READ-LIST-ROW #.(SB-SYS:INT-SAP #X00668DB0) ("table_schema" "table_name" "column_name" "data_type" "" "is_nullable" "" "CHARACTER_MAXIMUM_LENGTH" "NUMERIC_PRECISION" "NUMERIC_PRECISION_RADIX" "NUMERIC_SCALE" "DATETIME_PRECISION" "CHARACTER_SET_NAME" "COLLATION_NAME"))
2: (MSSQL::ALL-ROWS #.(SB-SYS:INT-SAP #X00668DB0) ("table_schema" "table_name" "column_name" "data_type" "" "is_nullable" "" "CHARACTER_MAXIMUM_LENGTH" "NUMERIC_PRECISION" "NUMERIC_PRECISION_RADIX" "NUMERIC_SCALE" "DATETIME_PRECISION" "CHARACTER_SET_NAME" "COLLATION_NAME") MSSQL::READ-LIST-ROW)
3: (MSSQL:QUERY "..." :CONNECTION #<MSSQL:DATABASE-CONNECTION {10099A80B3}> :FORMAT :LISTS)
4: (PGLOADER.MSSQL::LIST-ALL-COLUMNS :TABLE-TYPE :TABLE :INCLUDING NIL :EXCLUDING NIL)
5: (PGLOADER.MSSQL::FETCH-MSSQL-METADATA #<PGLOADER.MSSQL:COPY-MSSQL {1009790E03}> :STATE #S(PGLOADER.UTILS::PGSTATE :TABLES #<HASH-TABLE :TEST EQUAL :COUNT 1 {1008E3FE23}> :TABNAMES ("fetch meta data") :READ 0 :ROWS 0 :ERRS 0 :SECS 0.0) :INCLUDING NIL :EXCLUDING NIL)
6: ((:METHOD PGLOADER.SOURCES:COPY-DATABASE (PGLOADER.MSSQL:COPY-MSSQL)) #<PGLOADER.MSSQL:COPY-MSSQL {1009790E03}> :STATE-BEFORE #S(PGLOADER.UTILS::PGSTATE :TABLES #<HASH-TABLE :TEST EQUAL :COUNT 1 {1008E3FE23}> :TABNAMES ("fetch meta data") :READ 0 :ROWS 0 :ERRS 0 :SECS 0.0) :STATE-AFTER #S(PGLOADER.UTILS::PGSTATE :TABLES #<HASH-TABLE :TEST EQUAL :COUNT 0 {1008E46DA3}> :TABNAMES NIL :READ 0 :ROWS 0 :ERRS 0 :SECS 0.0) :STATE-INDEXES #S(PGLOADER.UTILS::PGSTATE :TABLES #<HASH-TABLE :TEST EQUAL :COUNT 0 {1008E46923}> :TABNAMES NIL :READ 0 :ROWS 0 :ERRS 0 :SECS 0.0) :TRUNCATE NIL :DISABLE-TRIGGERS NIL :DATA-ONLY NIL :SCHEMA-ONLY NIL :CREATE-TABLES T :CREATE-SCHEMAS T :INCLUDE-DROP NIL :CREATE-INDEXES T :RESET-SEQUENCES T :FOREIGN-KEYS T :ENCODING :UTF-8 :INCLUDING NIL :EXCLUDING NIL) [fast-method]
7: ((LAMBDA ()))
8: (PGLOADER:RUN-COMMANDS #P"..." :START-LOGGER NIL :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLIENT-MIN-MESSAGES NIL)
9: (PGLOADER::PROCESS-COMMAND-FILE "load.load")
10: ((FLET #:CLEANUP-FUN-285 :IN PGLOADER::MAIN)) [cleanup]
11: (PGLOADER::MAIN (".." "--debug" "--verbose" "load.load"))
12: ((LAMBDA NIL :IN "..."))
13: ((FLET #:WITHOUT-INTERRUPTS-BODY-85 :IN SAVE-LISP-AND-DIE))
14: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))
```

**Comment by dimitri** [comment]
As I just manually cherry-picked your patch for failure to realize there was this PR in the queue, I'm confused now about why github seems to think it would still apply...

**Comment by gavinwahl** [comment]
Any thoughts about the other bug @dimitri ?

**Comment by dimitri** [comment]
Well it looks like the freetds driver is actually sending us signed integer. Looking in the CFFI code, I notice that the notion of an `:unsigned-int` foreign type is present. Can you please try something along the lines of:

```diff
diff --git a/src/monkey/mssql.lisp b/src/monkey/mssql.lisp
index c910ed9..18da0e2 100644
--- a/src/monkey/mssql.lisp
+++ b/src/monkey/mssql.lisp
@@ -83,9 +83,9 @@
         ((:syb-varchar :syb-text) (foreign-string-to-lisp data :count len))
         (:syb-char (string-trim #(#\Space) (foreign-string-to-lisp data :count len)))
         ((:syb-bit :syb-bitn) (mem-ref data :int))
-        (:syb-int1 (unsigned-to-signed (mem-ref data :int) 1))
-        (:syb-int2 (unsigned-to-signed (mem-ref data :int) 2))
-        (:syb-int4 (unsigned-to-signed (mem-ref data :int) 4))
+        (:syb-int1 (unsigned-to-signed (mem-ref data :unsigned-int) 1))
+        (:syb-int2 (unsigned-to-signed (mem-ref data :unsigned-int) 2))
+        (:syb-int4 (unsigned-to-signed (mem-ref data :unsigned-int) 4))
         (:syb-int8 (mem-ref data :int8))
         (:syb-flt8 (mem-ref data :double))
         (:syb-datetime
```

**Comment by dimitri** [comment]
Did you have the opportunity to try this fix? Should I push it?

**Comment by gavinwahl** [comment]
I set `tds version = 8.0` to fix another issue and this problem went away.

**Comment by dimitri** [comment]
Oh. Then I need to see about forcing the protocol version from the driver directly, or to make that recommendation very visible in the docs... thanks for the follow-up.

**Pull request closed without merging**
