### PR TITLE
Fix DROP TABLE statements on tables with foreign keys

### PR DESCRIPTION
**Pull request by alexbaretta**

### CODE REVIEW

**Comment by dimitri** [comment]
What if you're loading a subset of the tables and using `WITH DROP`? I bet in that case it's better to have errors than to mistakenly drop the whole database table set?

**Comment by alexbaretta** [comment]
I think the current behavior defeats the purpose of `WITH DROP`. This option is supposed to allow the user to repeatedly run the same pgloader script without having to manually drop and recreate the database.

**Comment by dimitri** [comment]
That's true. Please amend the docs to reflect the `CASCADE` usage and its consequences (existing local tables are going to disappear, you will *LOSE* data, etc) then, and I will merge. Thanks!

**Comment by alexbaretta** [comment]
Dimitri, I updated the markdown doc, but I have no idea how to update pgloader.1. I assume it's groff, and I have no knowledge of it.

**Comment by dimitri** [comment]
There's a `make docs` target, but don't worry, I am due to fix the toolchain here and the manpage has not been updated when its source has been changed lately. Will take care of that before next release.

Can you rebase your pull request to make it a single commit, and fix *please not* into *please note* while at it? Thanks!

**Comment by alexbaretta** [comment]
Done.

**Comment by dimitri** [comment]
And merged, thanks!

**Comment by alexbaretta** [comment]
Awesome!

**Pull request merged**
