### PR TITLE
Allow dots in user names

### PR DESCRIPTION
**Pull request by pinaraf**
Fix issue #168 by adding . in the punct defrule.

### CODE REVIEW

**Comment by dimitri** [comment]
I don't think your fix can be used at all really, because the `punct` rule is used in the definition of a `namestring` and only there. The fix I envision would add a new `mysql-user-password` rule to use in the `mysql-uri` rule, wherein it's using a `mysql-username` rule that allows dots in names.

Do you want to see about that?

**Comment by pinaraf** [comment]
Well, my «fix» was enough to make it work for my need, but I understand it may be a terrible way to fix. It just seemed weird to me that a punct role did not include a dot… Well, must be a translation misunderstanding.
namestring is the rule used in a lot of rules, and is also used in the mysql user name rule.
I've modified my branch, I've not used the "mysql-username" name for the rule because that same rule is used for postgresql user name (that suffered from the same bug…)

**Comment by dimitri** [comment]
I'm not sure dots are allowed in PostgreSQL user names, will look into that. The problem with editing the  *namestring* rule is that it's then used for table names where dots are not allowed, as they are used as a separator in between a schema name and a table name.

**Comment by pinaraf** [comment]
Dots are allowed in PostgreSQL user names, we use them in production here.

**Comment by dimitri** [comment]
So, getting back to you, I see that your fix is actually correct, when I though you were still touching the *namestring* rule itself. Applying, thanks!

**Pull request merged**
