### PR TITLE
Fix convertion for msdatetime2

### PR DESCRIPTION
**Pull request by semenmiroshnichenko**
That solved https://github.com/dimitri/pgloader/issues/1018 for us.

### CODE REVIEW

**Comment by gjvoosten** [comment]
@dimitri Can this be merged? With the fix in the PR and the added cast in my config (and specifying a date format in my FreeTDS `locales.conf`) at least this mssql type is supported.

**Comment by dimitri** [comment]
To be able to apply that change (thanks for making it!), we need the MS SQL user face type name, and we need to know if we can use the SQL expression `"convert(varchar, [column name], 126)"` that we use already for other date time types here: https://github.com/dimitri/pgloader/blob/master/src/sources/mssql/mssql-schema.lisp#L166

**Comment by gjvoosten** [comment]
> To be able to apply that change (thanks for making it!), we need the MS SQL user face type name, and we need to know if we can use the SQL expression `"convert(varchar, [column name], 126)"` that we use already for other date time types here: https://github.com/dimitri/pgloader/blob/master/src/sources/mssql/mssql-schema.lisp#L166

Hi @dimitri , glad to see you back on track! Not sure what you're asking here, but the MS SQL type is `datetime2`: https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime2-transact-sql
From that page:
> Character length | 19 positions minimum (YYYY-MM-DD hh:mm:ss ) to 27 maximum (YYYY-MM-DD hh:mm:ss.0000000)
so I'm guessing that the conversion expression would work. If you want me to test something let me know.

**Comment by dimitri** [comment]
I just tried my luck with your change plus the CONVERT call to make sure we get something that Postgres likes. Please confirm that the new master's branch works for you.

**Comment by gjvoosten** [comment]
Hi @dimitri ! Just tried compiling the latest master, but I'm getting errors like:

> […]
> [package pgloader.sources]
> debugger invoked on a NAME-CONFLICT in thread
> #<THREAD "main thread" RUNNING {1000518083}>:
>   EXPORT PGLOADER.SOURCES::GET-COLUMN-LIST causes name-conflicts in
>   #<PACKAGE "PGLOADER.SOURCE.MSSQL"> between the following symbols:
>     PGLOADER.SOURCES::GET-COLUMN-LIST, PGLOADER.SOURCE.MSSQL::GET-COLUMN-LIST
> See also:
>   The ANSI Standard, Section 11.1.1.2.5
>
> Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
>
> restarts (invokable by number or by possibly-abbreviated name):
>   0: [KEEP-OLD                     ] Keep PGLOADER.SOURCE.MSSQL::GET-COLUMN-LIST accessible in PGLOADER.SOURCE.MSSQL (shadowing PGLOADER.SOURCES::GET-COLUMN-LIST).
>   1: [TAKE-NEW                     ] Make PGLOADER.SOURCES::GET-COLUMN-LIST accessible in PGLOADER.SOURCE.MSSQL (uninterning PGLOADER.SOURCE.MSSQL::GET-COLUMN-LIST).
>   2: [RESOLVE-CONFLICT             ] Resolve conflict.
>   3: [RETRY                        ] Retry
>                                      compiling #<CL-SOURCE-FILE "pgloader" "src" "package">.
>   4: [ACCEPT                       ] Continue, treating
>                                      compiling #<CL-SOURCE-FILE "pgloader" "src" "package">
>                                      as having been successful.
>   5:                                 Retry ASDF operation.
>   6: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
>                                      configuration.
>   7:                                 Retry ASDF operation.
>   8:                                 Retry ASDF operation after resetting the
>                                      configuration.
>   9: [ABORT                        ] Give up on "pgloader"
>  10: [CONTINUE                     ] Ignore runtime option --eval "(ql:quickload \"pgloader\")".
>  11:                                 Skip rest of --eval and --load options.
>  12:                                 Skip to toplevel READ/EVAL/PRINT loop.
>  13: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).
>
> (NAME-CONFLICT #<PACKAGE "PGLOADER.SOURCE.MSSQL"> EXPORT PGLOADER.SOURCES::GET-COLUMN-LIST PGLOADER.SOURCES::GET-COLUMN-LIST PGLOADER.SOURCE.MSSQL::GET-COLUMN-LIST)

Which versions of FreeTDS, SBCL etc. do I need to get a clean compile? I'm using the latest snapshot of FreeTDS (1.1.103 currently) and the latest SBCL (2.0.2 currently; although with 1.5.7 I'm getting similar errors). I also noticed that the [Travis CI builds](https://travis-ci.org/dimitri/pgloader/builds) are all failing. Let me know what I can do to help.

**Comment by phoe** [comment]
That's not a FreeTDS or SBCL issue - it would imply that the current pgloader master does not build due to errors in the Lisp source.

(A name conflict means that a package tries to import two distinct symbols with the same name into one package, and is often caused by changing package exports and not testing if this breaks anything.)

**Comment by gjvoosten** [comment]
EIther way, it would need to compile before I can test anything. :wink:

**Comment by phoe** [comment]
I can reproduce that issue.

```lisp
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10005184C3}>
0: (NAME-CONFLICT #<PACKAGE "PGLOADER.SOURCE.MSSQL"> EXPORT PGLOADER.SOURCES::GET-COLUMN-LIST PGLOADER.SOURCES::GET-COLUMN-LIST PGLOADER.SOURCE.MSSQL::GET-COLUMN-LIST)
1: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN EXPORT))
2: ((FLET "WITHOUT-INTERRUPTS-BODY-29" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
3: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN EXPORT) {7F87C64642BB}> #<SB-THREAD:MUTEX "Package Graph Lock" owner: #<SB-THREAD:THREAD "main thread" RUNNING {10005184C3}>> T NIL)
4: (EXPORT (PGLOADER.SOURCES:COPY PGLOADER.SOURCES:MD-COPY PGLOADER.SOURCES:DB-COPY PGLOADER.SOURCES:MAP-ROWS PGLOADER.SOURCES:COPY-COLUMN-LIST PGLOADER.SOURCES:DATA-IS-PREFORMATTED-P PGLOADER.SOURCES:PREPROCESS-ROW PGLOADER.SOURCES:SOURCE-DB PGLOADER.SOURCES:TARGET-DB PGLOADER.SOURCES:SOURCE PGLOADER.SOURCES:TARGET PGLOADER.SOURCES:FIELDS ...) #<PACKAGE "PGLOADER.SOURCES">)
5: (SB-IMPL::UPDATE-PACKAGE #<PACKAGE "PGLOADER.SOURCES"> NIL #S(SB-C:DEFINITION-SOURCE-LOCATION :NAMESTRING "/home/phoe/Projects/Lisp/pgloader/src/package.lisp" :INDICES 524289) NIL NIL (#<PACKAGE "COMMON-LISP"> #<PACKAGE "PGLOADER.PARAMS"> #<PACKAGE "PGLOADER.UTILS"> #<PACKAGE "PGLOADER.CONNECTION">) (PGLOADER.TRANSFORMS:TYPEMOD-EXPR-TO-FUNCTION PGLOADER.TRANSFORMS:TYPEMOD-EXPR-MATCHES-P PGLOADER.TRANSFORMS:PARSE-COLUMN-TYPEMOD PGLOADER.TRANSFORMS:INTERN-SYMBOL PGLOADER.TRANSFORMS:SCALE PGLOADER.TRANSFORMS:PRECISION PGLOADER.PARSE-DATE:PARSE-DATE-FORMAT PGLOADER.PARSE-DATE:PARSE-DATE-STRING) NIL ("COPY" "MD-COPY" "DB-COPY" "MAP-ROWS" "COPY-COLUMN-LIST" "DATA-IS-PREFORMATTED-P" "PREPROCESS-ROW" "SOURCE-DB" "TARGET-DB" "SOURCE" "TARGET" "FIELDS" ...) ("PGLOADER.SOURCES") NIL NIL NIL)
6: ((FLET "WITHOUT-INTERRUPTS-BODY-29" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
7: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN SB-IMPL::%DEFPACKAGE) {7F87C646455B}> #<SB-THREAD:MUTEX "Package Graph Lock" owner: #<SB-THREAD:THREAD "main thread" RUNNING {10005184C3}>> T NIL)
8: (SB-IMPL::%DEFPACKAGE "PGLOADER.SOURCES" NIL NIL NIL NIL ("CL" "PGLOADER.PARAMS" "PGLOADER.UTILS" "PGLOADER.CONNECTION") (("PGLOADER.PARSE-DATE" "PARSE-DATE-STRING" "PARSE-DATE-FORMAT") ("PGLOADER.TRANSFORMS" "PRECISION" "SCALE" "INTERN-SYMBOL" "PARSE-COLUMN-TYPEMOD" "TYPEMOD-EXPR-MATCHES-P" "TYPEMOD-EXPR-TO-FUNCTION")) NIL ("COPY" "MD-COPY" "DB-COPY" "MAP-ROWS" "COPY-COLUMN-LIST" "DATA-IS-PREFORMATTED-P" "PREPROCESS-ROW" "SOURCE-DB" "TARGET-DB" "SOURCE" "TARGET" "FIELDS" ...) ("PGLOADER.SOURCES") NIL NIL #S(SB-C:DEFINITION-SOURCE-LOCATION :NAMESTRING "/home/phoe/Projects/Lisp/pgloader/src/package.lisp" :INDICES 524289) NIL)
9: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SB-IMPL::%DEFPACKAGE #1="PGLOADER.SOURCES" (QUOTE NIL) (QUOTE NIL) (QUOTE NIL) (QUOTE NIL) (QUOTE ("CL" "PGLOADER.PARAMS" "PGLOADER.UTILS" "PGLOADER.CONNECTION")) (QUOTE (("PGLOADER.PARSE-DATE" "PARSE-DATE-STRING" "PARSE-DATE-FORMAT") ("PGLOADER.TRANSFORMS" "PRECISION" "SCALE" "INTERN-SYMBOL" "PARSE-COLUMN-TYPEMOD" "TYPEMOD-EXPR-MATCHES-P" "TYPEMOD-EXPR-TO-FUNCTION"))) (QUOTE NIL) (QUOTE ("COPY" "MD-COPY" "DB-COPY" "MAP-ROWS" "COPY-COLUMN-LIST" "DATA-IS-PREFORMATTED-P" "PREPROCESS-ROW" "SOURCE-DB" "TARGET-DB" "SOURCE" "TARGET" "FIELDS" ...)) (QUOTE (#1#)) (QUOTE NIL) ...) #<NULL-LEXENV>)
```

**Comment by phoe** [comment]
@gjvoosten I have created #1090 for this issue. Thanks for the report, I'm looking into it now.

**Comment by gjvoosten** [comment]
> I just tried my luck with your change plus the CONVERT call to make sure we get something that Postgres likes. Please confirm that the new master's branch works for you.

@dimitri Yes, the fix seems to work (when building pgloader from the #1090 branch). Apologies for the delay in responding.

**Pull request closed without merging**
