### PR TITLE
>= 10 instead of <= 10

### PR DESCRIPTION
**Pull request by alexknips**
the given explanation seemed wrong

### CODE REVIEW

**Comment by dimitri** [comment]
Thanks!

**Comment by alexknips** [comment]
Do you also need to fix it in code or is the code correct?

**Comment by dimitri** [comment]
The code is correct, have a look at https://github.com/dimitri/pgloader/blob/master/src/sources/mysql/mysql-cast-rules.lisp#L25 and around.

**Comment by alexknips** [comment]
got it. not that familiar with LISP. Thx for the clarification.

**Pull request merged**
