### PR TITLE
Two bugfixes

### PR DESCRIPTION
**Pull request by alexbaretta**
* Fix identifier case in FOREIGN KEY constraints
* Fix string delimiter syntax in COMMENT statements

### CODE REVIEW

**Comment by dimitri** [comment]
Hi, thanks for the fix!

I don' t understand what you are achieving in the 5b3fb6fd1106331afb4c5ed842e400831f206351 patch tho, can you expand on that? All I can see is weakening of the poor man's dollar quoting protection I put into place here...

**Comment by alexbaretta** [comment]
Hey Dmitri,

Thanks for taking time to look into this. The rationale for 5b3fb6f is that dashes are not supported in $-delimiter strings.

main=# select $ABC-DEF$Hello, Dmitri!$ABC-DEF$;
ERROR:  syntax error at or near "$"
LINE 1: select $ABC-DEF$Hello, Dmitri!$ABC-DEF$;
               ^

**Comment by dimitri** [comment]
I am confused, because I (of course) tested that feature. Now it could be that the test case was wrong and didn't use the code path :( Anyways, can you amend your patch here to use "_" rather than "-", please?

**Comment by alexbaretta** [comment]
main=# select $ABC_DEF$Hello, Dmitri!$ABC_DEF$;
    ?column?    
----------------
 Hello, Dmitri!
(1 row)

I guess I can...

**Comment by dimitri** [comment]
Thanks!

**Comment by alexbaretta** [comment]
My pleasure!

**Pull request merged**
